name: pregassist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_intent_plus: ^6.0.0
  external_app_launcher: ^4.0.3
  http: ^1.2.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  flutter_onnxruntime: ^1.6.1
  carousel_slider: ^5.0.0
  flutter_tts: ^4.2.5
  camera: any
  permission_handler: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/fetal_model_manual_12c_nozipmap.onnx
    - assets/manual_12c_features.json
    - assets/explainability/shadow_tree_manual12_depth6_balanced_v2.json
    - assets/explainability/shadow_tree_manual12_depth6_balanced_v2_meta.json
