import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  static Future<void> generateAndPrintReport(Map<String, dynamic> resultData) async {
    final pdf = pw.Document();

    // Load Unicode-supported fonts via PdfGoogleFonts (no font files needed)
    final font     = await PdfGoogleFonts.robotoRegular();
    final boldFont = await PdfGoogleFonts.robotoBold();

    String title     = "Maternal Health Report";
    String riskLevel = resultData["risk_level"]?.toString().toUpperCase() ?? "UNKNOWN";
    String confidence= resultData["confidence"]?.toString() ?? "N/A";
    String date      = resultData["createdAt"] != null
        ? resultData["createdAt"].toString().substring(0, 10)
        : DateTime.now().toString().substring(0, 10);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'PregAssist',
                      style: pw.TextStyle(font: boldFont, fontSize: 24, color: PdfColors.blue800),
                    ),
                    pw.Text('Date: $date', style: pw.TextStyle(font: font, fontSize: 14)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                title,
                style: pw.TextStyle(font: boldFont, fontSize: 28, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 20),
              pw.Container(
                padding: const pw.EdgeInsets.all(15),
                decoration: pw.BoxDecoration(
                  color: riskLevel == "HIGH RISK"
                      ? PdfColors.red100
                      : (riskLevel == "MID RISK" ? PdfColors.orange100 : PdfColors.green100),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
                  border: pw.Border.all(
                    color: riskLevel == "HIGH RISK"
                        ? PdfColors.red
                        : (riskLevel == "MID RISK" ? PdfColors.orange : PdfColors.green),
                  ),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Risk Level: $riskLevel',
                      style: pw.TextStyle(
                        font: boldFont,
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                        color: riskLevel == "HIGH RISK" ? PdfColors.red900 : PdfColors.black,
                      ),
                    ),
                    pw.Text(
                      'Confidence: $confidence%',
                      style: pw.TextStyle(font: font, fontSize: 16),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),
              pw.Text(
                'Health Parameters',
                style: pw.TextStyle(font: boldFont, fontSize: 20, fontWeight: pw.FontWeight.bold),
              ),
              pw.Divider(),
              pw.SizedBox(height: 10),
              _row('Pregnancy Week',    resultData['Week']?.toString()      ?? 'N/A', font, boldFont),
              _row('Age',               resultData['Age']?.toString()       ?? 'N/A', font, boldFont),
              _row('Blood Pressure',    '${resultData['SystolicBP'] ?? 'N/A'}/${resultData['DiastolicBP'] ?? 'N/A'} mmHg', font, boldFont),
              _row('Blood Sugar',       '${resultData['BS'] ?? 'N/A'} mmol/L', font, boldFont),
              _row('Heart Rate',        '${resultData['HeartRate'] ?? 'N/A'} bpm', font, boldFont),
              _row('Body Temperature',  '${resultData['BodyTemp'] ?? 'N/A'} °C', font, boldFont),
              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text(
                  'Generated by PregAssist AI - For informational purposes only.',
                  style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey),
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Maternal_Health_Report_$date.pdf',
    );
  }

  static pw.Widget _row(String label, String value, pw.Font font, pw.Font boldFont) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 5),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 16)),
          pw.Text(value,  style: pw.TextStyle(font: boldFont, fontSize: 16, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
